services:
  api-backend:
    container_name: api-backend-container
    image: tech-post-cast-api-backend
    build:
      context: .
      dockerfile: Dockerfile.api-backend
    ports:
      - '3001:3001'
    env_file:
      - apps/api-backend/.env
    environment:
      - PORT=3001
      - NODE_ENV=development
      - SHOW_QUERY_LOGS=true
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:5432/techpostcast
  backend:
    container_name: backend-container
    image: tech-post-cast-backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - '3000:3000'
    env_file:
      - apps/infra/.env.develop
      # - docker_compose.backend.env
      - apps/backend/.env
    environment:
      - PORT=3000
      - NODE_ENV=development
      - SHOW_QUERY_LOGS=true
      # ffmpeg
      - FFMPEG_PATH=/usr/bin/ffmpeg
      - FFPROBE_PATH=/usr/bin/ffprobe
      # OpenAI
      - OPEN_AI_SUMMARIZATION_MODEL=gpt-4o-mini
      - OPEN_AI_SCRIPT_GENERATION_MODEL=gpt-4o
      # 番組ファイル生成で利用する一時ファイルの保存先
      - PROGRAM_FILE_GENERATION_TEMP_DIR=/tmp/program-file-maker
      # ヘッドライントピック番組用音声ファイル
      - HEADLINE_TOPIC_PROGRAM_TARGET_DIR=/tmp/headline-topic-programs
      - HEADLINE_TOPIC_PROGRAM_BGM_FILE_PATH=assets/audio/headline-topic-programs/bgm.mp3
      - HEADLINE_TOPIC_PROGRAM_OPENING_FILE_PATH=assets/audio/headline-topic-programs/opening.mp3
      - HEADLINE_TOPIC_PROGRAM_ENDING_FILE_PATH=assets/audio/headline-topic-programs/ending.mp3
      - HEADLINE_TOPIC_PROGRAM_PICTURE_FILE_PATH=assets/audio/headline-topic-programs/preview.jpg
      - HEADLINE_TOPIC_PROGRAM_SE_SHORT_FILE_PATH=assets/audio/headline-topic-programs/se_short.mp3
      - HEADLINE_TOPIC_PROGRAM_SE_LONG_FILE_PATH=assets/audio/headline-topic-programs/se_long.mp3
      # パーソナルプログラム用音声ファイル
      - PERSONALIZED_PROGRAM_TARGET_DIR=/tmp/personalized-programs
      - PERSONALIZED_PROGRAM_BGM_FILE_PATH=assets/audio/personalized-programs/bgm.mp3
      - PERSONALIZED_PROGRAM_OPENING_FILE_PATH=assets/audio/personalized-programs/opening.mp3
      - PERSONALIZED_PROGRAM_ENDING_FILE_PATH=assets/audio/personalized-programs/ending.mp3
      - PERSONALIZED_PROGRAM_SE_1_FILE_PATH=assets/audio/personalized-programs/se_1.mp3
      - PERSONALIZED_PROGRAM_SE_2_FILE_PATH=assets/audio/personalized-programs/se_2.mp3
      - PERSONALIZED_PROGRAM_SE_3_FILE_PATH=assets/audio/personalized-programs/se_3.mp3
      - PERSONALIZED_PROGRAM_PICTURE_FILE_PATH=assets/audio/personalized-programs/preview.jpg
      # Database
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:5432/techpostcast
  db:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: techpostcast
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
