services:
  backend:
    container_name: tech-post-cast
    image: tech-post-cast-backend
    build: 
      context: .
      dockerfile: Dockerfile.backend
    # volumes:
    #   - .:/app
    ports:
      - '3000:3000'
    env_file:
      - docker_compose.backend.env
    environment:
      - NODE_ENV=development
      - SHOW_QUERY_LOGS=true
      # ffmpeg
      - FFMPEG_PATH=/usr/bin/ffmpeg
      - FFPROBE_PATH=/usr/bin/ffprobe
      # ヘッドライントピック番組用音声ファイル
      - HEADLINE_TOPIC_PROGRAM_TARGET_DIR=/tmp/headline-topic-programs
      - HEADLINE_TOPIC_PROGRAM_BGM_FILE_PATH=assets/audio/headline-topic-programs/bgm.mp3
      - HEADLINE_TOPIC_PROGRAM_OPENING_FILE_PATH=assets/audio/headline-topic-programs/opening.mp3
      - HEADLINE_TOPIC_PROGRAM_ENDING_FILE_PATH=assets/audio/headline-topic-programs/ending.mp3
      - HEADLINE_TOPIC_PROGRAM_PICTURE_FILE_PATH=assets/audio/headline-topic-programs/preview.jpg
      # AWS
      - PROGRAM_AUDIO_BUCKET_NAME=tech-post-cast-program-audio-bucket-develop
      - PROGRAM_AUDIO_FILE_URL_PREFIX=https://d2ohwgmlpn9j5f.cloudfront.net
