version: '3.9'
services:
  backend:
    container_name: tech-post-cast
    image: tech-post-cast-backend
    build: 
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - .:/app
    ports:
      - '3000:3000'
