services:
  backend:
    container_name: backend-container
    image: tech-post-cast-backend
    build: 
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - '3000:3000'
    env_file:
      - apps/infra/.env.develop
      - docker_compose.backend.env
    environment:
      - PORT=3000
      - NODE_ENV=development
      - SHOW_QUERY_LOGS=true
      # ffmpeg
      - FFMPEG_PATH=/usr/bin/ffmpeg
      - FFPROBE_PATH=/usr/bin/ffprobe
      # OpenAI
      - OPEN_AI_SUMMARIZATION_MODEL=gpt-4o-mini
      - OPEN_AI_SCRIPT_GENERATION_MODEL=gpt-4o
      # 番組ファイル生成で利用する一時ファイルの保存先
      - HEADLINE_TOPIC_PROGRAM_TARGET_DIR=/tmp/headline-topic-programs
      - PROGRAM_FILE_GENERATION_TEMP_DIR=/tmp/program-file-maker
      # ヘッドライントピック番組用音声ファイル
      - HEADLINE_TOPIC_PROGRAM_BGM_FILE_PATH=assets/audio/headline-topic-programs/bgm.mp3
      - HEADLINE_TOPIC_PROGRAM_OPENING_FILE_PATH=assets/audio/headline-topic-programs/opening.mp3
      - HEADLINE_TOPIC_PROGRAM_ENDING_FILE_PATH=assets/audio/headline-topic-programs/ending.mp3
      - HEADLINE_TOPIC_PROGRAM_PICTURE_FILE_PATH=assets/audio/headline-topic-programs/preview.jpg
      - HEADLINE_TOPIC_PROGRAM_SE_SHORT_FILE_PATH=assets/audio/headline-topic-programs/se_short.mp3
      - HEADLINE_TOPIC_PROGRAM_SE_LONG_FILE_PATH=assets/audio/headline-topic-programs/se_long.mp3
