version: '3.9'
services:
  backend:
    container_name: tech-post-cast
    image: tech-post-cast-backend
    build: 
      context: .
      dockerfile: Dockerfile.backend
    # volumes:
    #   - .:/app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - FFMPEG_PATH=/usr/bin/ffmpeg
      - FFPROBE_PATH=/usr/bin/ffprobe
