##################################################
# フロント向け API (v1) の実行
##################################################

# ローカル環境
@baseUrl = {{$dotenv BACKEND_BASE_URL_LOCAL}}
@apiToken = {{$dotenv V1_API_TOKEN_LOCAL}}

# 開発環境
# @baseUrl = {{$dotenv BACKEND_BASE_URL_DEV}}
# @apiToken = {{$dotenv V1_API_TOKEN_DEV}}

# 本番環境
# @baseUrl = {{$dotenv BACKEND_BASE_URL_PROD}}
# @apiToken = {{$dotenv V1_API_TOKEN_PROD}}


### ヘッドライントピック番組の件数を取得する
GET {{baseUrl}}/api/v1/headline-topic-programs/count
Content-Type: application/json
Authorization: Bearer {{apiToken}}

### ヘッドライントピック番組の一覧を取得する
@limit=10
@page=1
GET {{baseUrl}}/api/v1/headline-topic-programs?limit={{limit}}&page={{page}}
Content-Type: application/json
Authorization: Bearer {{apiToken}}

### ヘッドライントピック番組の番組ID一覧を取得する
GET {{baseUrl}}/api/v1/headline-topic-program-ids
Content-Type: application/json
Authorization: Bearer {{apiToken}}

### 指定のヘッドライントピック番組を取得する
@postId = cm6d7ey420000jx0ypb6sivhu
GET {{baseUrl}}/api/v1/headline-topic-programs/{{postId}}
Content-Type: application/json
Authorization: Bearer {{apiToken}}

### 指定のヘッドライントピック番組および、前後の日付の番組を取得する
@postId = cm6d7ey420000jx0ypb6sivhu
GET {{baseUrl}}/api/v1/headline-topic-programs/{{postId}}/neighbors
Content-Type: application/json
Authorization: Bearer {{apiToken}}
