# @baseUrl = http://localhost:3000
# @baseUrl = https://v0q3zp560g.execute-api.ap-northeast-1.amazonaws.com/
@baseUrl = https://9xsg0utwm0.execute-api.ap-northeast-1.amazonaws.com/

POST {{baseUrl}}/headline-topic-programs
# x-amzn-lambda-context: {"request_id":"85203a83-e02c-4284-b6dd-3f0def1ae128","deadline":1723132633704}
Content-Type: application/json
Authorization: Bearer xxxxxxxxxxxffffffffffff

{
  "daysAgo": 0
}

