##################################################
# 通知バッチAPIの実行
##################################################

# ローカル環境
@baseUrl = {{$dotenv BACKEND_BASE_URL_LOCAL}}
@accessToken = {{$dotenv BACKEND_API_TOKEN_LOCAL}}

# 開発環境
# @baseUrl = {{$dotenv BACKEND_BASE_URL_DEV}}

# 本番環境
# @baseUrl = {{$dotenv BACKEND_BASE_URL_PROD}}

##################################################
# パーソナルプログラム生成結果の一括通知送信
##################################################

### 通知バッチ処理の実行
POST {{baseUrl}}/notifications/batch
Content-Type: application/json
Authorization: Bearer {{accessToken}}

# リクエストボディは不要（前日分の未通知レコードを自動処理）
{}
