@apiBaseUrl = http://localhost:3001

### Qiita記事検索API
# パラメータなしで検索（全記事取得）
GET {{apiBaseUrl}}/qiita-posts/search
Content-Type: application/json

### 著者指定で検索
GET {{apiBaseUrl}}/qiita-posts/search?authors=sumihiro3,fumikoba3
Content-Type: application/json

### タグ指定で検索
GET {{apiBaseUrl}}/qiita-posts/search?tags=JavaScript,TypeScript
Content-Type: application/json

### 公開日指定で検索
GET {{apiBaseUrl}}/qiita-posts/search?minPublishedAt=2023-01-01
Content-Type: application/json

### 複数条件を組み合わせた検索
GET {{apiBaseUrl}}/qiita-posts/search?authors=sumihiro3&tags=LINE,Nuxt3,TypeScript&minPublishedAt=2010-01-01&perPage=100
Content-Type: application/json

### 複数条件を組み合わせた検索
GET {{apiBaseUrl}}/qiita-posts/search?tags=LINE,Nuxt3,TypeScript&minPublishedAt=2010-01-01&perPage=100
Content-Type: application/json

### ページネーションを指定した検索（2ページ目、1ページ10件）
GET {{apiBaseUrl}}/qiita-posts/search?page=2&perPage=10
Content-Type: application/json

### 全条件を組み合わせた検索
GET {{apiBaseUrl}}/qiita-posts/search?authors=sumihiro&tags=typescript&minPublishedAt=2023-01-01&page=1&perPage=20
Content-Type: application/json
