/* tslint:disable */
/* eslint-disable */
/**
 * TechPostCast APIs
 * API document for TechPostCast APIs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface HeadlineTopicProgramDto
 */
export interface HeadlineTopicProgramDto {
    /**
     * 番組ID
     * @type {string}
     * @memberof HeadlineTopicProgramDto
     */
    'id': string;
    /**
     * タイトル
     * @type {string}
     * @memberof HeadlineTopicProgramDto
     */
    'title': string;
}
/**
 * 
 * @export
 * @interface HeadlineTopicProgramsFindRequestDto
 */
export interface HeadlineTopicProgramsFindRequestDto {
    /**
     * ページあたりに取得する番組の数
     * @type {number}
     * @memberof HeadlineTopicProgramsFindRequestDto
     */
    'limit': number;
    /**
     * ページ番号
     * @type {number}
     * @memberof HeadlineTopicProgramsFindRequestDto
     */
    'page'?: number;
}

/**
 * ApiV1Api - axios parameter creator
 * @export
 */
export const ApiV1ApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 指定のヘッドライントピック番組を取得する
         * @param {string} id 
         * @param {string} xApiKey API Key
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1GetHeadlineTopicProgram: async (id: string, xApiKey: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiV1GetHeadlineTopicProgram', 'id', id)
            // verify required parameter 'xApiKey' is not null or undefined
            assertParamExists('apiV1GetHeadlineTopicProgram', 'xApiKey', xApiKey)
            const localVarPath = `/api/v1/headline-topic-programs/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (xApiKey != null) {
                localVarHeaderParameter['x-api-key'] = String(xApiKey);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary ヘッドライントピック番組の一覧を取得する
         * @param {string} xApiKey API Key
         * @param {HeadlineTopicProgramsFindRequestDto} headlineTopicProgramsFindRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1GetHeadlineTopicPrograms: async (xApiKey: string, headlineTopicProgramsFindRequestDto: HeadlineTopicProgramsFindRequestDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xApiKey' is not null or undefined
            assertParamExists('apiV1GetHeadlineTopicPrograms', 'xApiKey', xApiKey)
            // verify required parameter 'headlineTopicProgramsFindRequestDto' is not null or undefined
            assertParamExists('apiV1GetHeadlineTopicPrograms', 'headlineTopicProgramsFindRequestDto', headlineTopicProgramsFindRequestDto)
            const localVarPath = `/api/v1/headline-topic-programs`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (xApiKey != null) {
                localVarHeaderParameter['x-api-key'] = String(xApiKey);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(headlineTopicProgramsFindRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary ヘッドライントピック番組の件数を取得する
         * @param {string} xApiKey API Key
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1GetHeadlineTopicProgramsCounts: async (xApiKey: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xApiKey' is not null or undefined
            assertParamExists('apiV1GetHeadlineTopicProgramsCounts', 'xApiKey', xApiKey)
            const localVarPath = `/api/v1/headline-topic-programs/count`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (xApiKey != null) {
                localVarHeaderParameter['x-api-key'] = String(xApiKey);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ApiV1Api - functional programming interface
 * @export
 */
export const ApiV1ApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ApiV1ApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 指定のヘッドライントピック番組を取得する
         * @param {string} id 
         * @param {string} xApiKey API Key
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1GetHeadlineTopicProgram(id: string, xApiKey: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HeadlineTopicProgramDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1GetHeadlineTopicProgram(id, xApiKey, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ApiV1Api.apiV1GetHeadlineTopicProgram']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary ヘッドライントピック番組の一覧を取得する
         * @param {string} xApiKey API Key
         * @param {HeadlineTopicProgramsFindRequestDto} headlineTopicProgramsFindRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1GetHeadlineTopicPrograms(xApiKey: string, headlineTopicProgramsFindRequestDto: HeadlineTopicProgramsFindRequestDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1GetHeadlineTopicPrograms(xApiKey, headlineTopicProgramsFindRequestDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ApiV1Api.apiV1GetHeadlineTopicPrograms']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary ヘッドライントピック番組の件数を取得する
         * @param {string} xApiKey API Key
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1GetHeadlineTopicProgramsCounts(xApiKey: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1GetHeadlineTopicProgramsCounts(xApiKey, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ApiV1Api.apiV1GetHeadlineTopicProgramsCounts']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ApiV1Api - factory interface
 * @export
 */
export const ApiV1ApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ApiV1ApiFp(configuration)
    return {
        /**
         * 
         * @summary 指定のヘッドライントピック番組を取得する
         * @param {string} id 
         * @param {string} xApiKey API Key
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1GetHeadlineTopicProgram(id: string, xApiKey: string, options?: RawAxiosRequestConfig): AxiosPromise<HeadlineTopicProgramDto> {
            return localVarFp.apiV1GetHeadlineTopicProgram(id, xApiKey, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary ヘッドライントピック番組の一覧を取得する
         * @param {string} xApiKey API Key
         * @param {HeadlineTopicProgramsFindRequestDto} headlineTopicProgramsFindRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1GetHeadlineTopicPrograms(xApiKey: string, headlineTopicProgramsFindRequestDto: HeadlineTopicProgramsFindRequestDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiV1GetHeadlineTopicPrograms(xApiKey, headlineTopicProgramsFindRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary ヘッドライントピック番組の件数を取得する
         * @param {string} xApiKey API Key
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1GetHeadlineTopicProgramsCounts(xApiKey: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiV1GetHeadlineTopicProgramsCounts(xApiKey, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ApiV1Api - object-oriented interface
 * @export
 * @class ApiV1Api
 * @extends {BaseAPI}
 */
export class ApiV1Api extends BaseAPI {
    /**
     * 
     * @summary 指定のヘッドライントピック番組を取得する
     * @param {string} id 
     * @param {string} xApiKey API Key
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiV1Api
     */
    public apiV1GetHeadlineTopicProgram(id: string, xApiKey: string, options?: RawAxiosRequestConfig) {
        return ApiV1ApiFp(this.configuration).apiV1GetHeadlineTopicProgram(id, xApiKey, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary ヘッドライントピック番組の一覧を取得する
     * @param {string} xApiKey API Key
     * @param {HeadlineTopicProgramsFindRequestDto} headlineTopicProgramsFindRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiV1Api
     */
    public apiV1GetHeadlineTopicPrograms(xApiKey: string, headlineTopicProgramsFindRequestDto: HeadlineTopicProgramsFindRequestDto, options?: RawAxiosRequestConfig) {
        return ApiV1ApiFp(this.configuration).apiV1GetHeadlineTopicPrograms(xApiKey, headlineTopicProgramsFindRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary ヘッドライントピック番組の件数を取得する
     * @param {string} xApiKey API Key
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiV1Api
     */
    public apiV1GetHeadlineTopicProgramsCounts(xApiKey: string, options?: RawAxiosRequestConfig) {
        return ApiV1ApiFp(this.configuration).apiV1GetHeadlineTopicProgramsCounts(xApiKey, options).then((request) => request(this.axios, this.basePath));
    }
}



