/* tslint:disable */
/* eslint-disable */
/**
 * TechPostCast API
 * TechPostCast API for frontend application
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface HeadlineTopicProgramChapterDto
 */
export interface HeadlineTopicProgramChapterDto {
    /**
     * タイトル
     * @type {string}
     * @memberof HeadlineTopicProgramChapterDto
     */
    'title': string;
    /**
     * チャプターの開始位置（ミリ秒）
     * @type {number}
     * @memberof HeadlineTopicProgramChapterDto
     */
    'startTime': number;
    /**
     * チャプターの終了位置（ミリ秒）
     * @type {number}
     * @memberof HeadlineTopicProgramChapterDto
     */
    'endTime': number;
}
/**
 * 
 * @export
 * @interface HeadlineTopicProgramDto
 */
export interface HeadlineTopicProgramDto {
    /**
     * 番組ID
     * @type {string}
     * @memberof HeadlineTopicProgramDto
     */
    'id': string;
    /**
     * タイトル
     * @type {string}
     * @memberof HeadlineTopicProgramDto
     */
    'title': string;
    /**
     * 台本
     * @type {HeadlineTopicProgramScriptDto}
     * @memberof HeadlineTopicProgramDto
     */
    'script': HeadlineTopicProgramScriptDto;
    /**
     * ヘッドライントピック番組のチャプター一覧
     * @type {Array<HeadlineTopicProgramChapterDto>}
     * @memberof HeadlineTopicProgramDto
     */
    'chapters': Array<HeadlineTopicProgramChapterDto>;
    /**
     * ヘッドライントピックの音声ファイルURL
     * @type {string}
     * @memberof HeadlineTopicProgramDto
     */
    'audioUrl': string;
    /**
     * 音声ファイルの長さ（ミリ秒）
     * @type {number}
     * @memberof HeadlineTopicProgramDto
     */
    'audioDuration': number;
    /**
     * ヘッドライントピックの動画ファイルURL
     * @type {string}
     * @memberof HeadlineTopicProgramDto
     */
    'videoUrl'?: string;
    /**
     * 画像URL
     * @type {string}
     * @memberof HeadlineTopicProgramDto
     */
    'imageUrl'?: string;
    /**
     * 今日のヘッドライントピックが作成された日時
     * @type {string}
     * @memberof HeadlineTopicProgramDto
     */
    'createdAt': string;
    /**
     * 最終更新日時
     * @type {string}
     * @memberof HeadlineTopicProgramDto
     */
    'updatedAt': string;
    /**
     * 紹介している投稿の一覧
     * @type {Array<QiitaPostDto>}
     * @memberof HeadlineTopicProgramDto
     */
    'posts': Array<QiitaPostDto>;
}
/**
 * 
 * @export
 * @interface HeadlineTopicProgramScriptDto
 */
export interface HeadlineTopicProgramScriptDto {
    /**
     * タイトル
     * @type {string}
     * @memberof HeadlineTopicProgramScriptDto
     */
    'title': string;
    /**
     * イントロダクション
     * @type {string}
     * @memberof HeadlineTopicProgramScriptDto
     */
    'intro': string;
    /**
     * 紹介記事の要約
     * @type {Array<PostSummaryDto>}
     * @memberof HeadlineTopicProgramScriptDto
     */
    'posts': Array<PostSummaryDto>;
    /**
     * エンディング
     * @type {string}
     * @memberof HeadlineTopicProgramScriptDto
     */
    'ending': string;
}
/**
 * 
 * @export
 * @interface HeadlineTopicProgramWithSimilarAndNeighborsDto
 */
export interface HeadlineTopicProgramWithSimilarAndNeighborsDto {
    /**
     * 類似のヘッドライントピック番組
     * @type {Array<HeadlineTopicProgramDto>}
     * @memberof HeadlineTopicProgramWithSimilarAndNeighborsDto
     */
    'similar': Array<HeadlineTopicProgramDto>;
    /**
     * 前日のヘッドライントピック番組
     * @type {HeadlineTopicProgramDto}
     * @memberof HeadlineTopicProgramWithSimilarAndNeighborsDto
     */
    'previous': HeadlineTopicProgramDto;
    /**
     * 指定のヘッドライントピック番組
     * @type {HeadlineTopicProgramDto}
     * @memberof HeadlineTopicProgramWithSimilarAndNeighborsDto
     */
    'target': HeadlineTopicProgramDto;
    /**
     * 翌日のヘッドライントピック番組
     * @type {HeadlineTopicProgramDto}
     * @memberof HeadlineTopicProgramWithSimilarAndNeighborsDto
     */
    'next': HeadlineTopicProgramDto;
}
/**
 * 
 * @export
 * @interface HeadlineTopicProgramsCountDto
 */
export interface HeadlineTopicProgramsCountDto {
    /**
     * 番組数
     * @type {number}
     * @memberof HeadlineTopicProgramsCountDto
     */
    'count': number;
}
/**
 * 
 * @export
 * @interface PostSummaryDto
 */
export interface PostSummaryDto {
    /**
     * 記事の要約
     * @type {string}
     * @memberof PostSummaryDto
     */
    'summary': string;
}
/**
 * 
 * @export
 * @interface QiitaPostDto
 */
export interface QiitaPostDto {
    /**
     * 記事本文（Markdown形式）
     * @type {string}
     * @memberof QiitaPostDto
     */
    'body': string;
    /**
     * リアクション数
     * @type {number}
     * @memberof QiitaPostDto
     */
    'reactions_count': number;
    /**
     * 非公開記事かどうか
     * @type {boolean}
     * @memberof QiitaPostDto
     */
    'private': boolean;
    /**
     * 共同編集状態かどうか
     * @type {boolean}
     * @memberof QiitaPostDto
     */
    'coediting': boolean;
    /**
     * グループ情報
     * @type {object}
     * @memberof QiitaPostDto
     */
    'group': object;
    /**
     * ページビュー数
     * @type {number}
     * @memberof QiitaPostDto
     */
    'page_views_count'?: number;
    /**
     * チームメンバーシップ情報
     * @type {object}
     * @memberof QiitaPostDto
     */
    'team_membership': object;
    /**
     * 組織のURL名
     * @type {string}
     * @memberof QiitaPostDto
     */
    'organization_url_name'?: string;
    /**
     * スライド形式の記事かどうか
     * @type {boolean}
     * @memberof QiitaPostDto
     */
    'slide': boolean;
    /**
     * 記事の要約
     * @type {string}
     * @memberof QiitaPostDto
     */
    'summary'?: string;
    /**
     * 記事の一意なID
     * @type {string}
     * @memberof QiitaPostDto
     */
    'id': string;
    /**
     * 記事のタイトル
     * @type {string}
     * @memberof QiitaPostDto
     */
    'title': string;
    /**
     * 記事のURL
     * @type {string}
     * @memberof QiitaPostDto
     */
    'url': string;
    /**
     * 記事が作成された日時
     * @type {string}
     * @memberof QiitaPostDto
     */
    'created_at': string;
    /**
     * 記事の最終更新日時
     * @type {string}
     * @memberof QiitaPostDto
     */
    'updated_at': string;
    /**
     * 記事投稿者
     * @type {QiitaUserDto}
     * @memberof QiitaPostDto
     */
    'user': QiitaUserDto;
    /**
     * この記事へのコメントの数
     * @type {number}
     * @memberof QiitaPostDto
     */
    'comments_count': number;
    /**
     * この記事へのいいねの数
     * @type {number}
     * @memberof QiitaPostDto
     */
    'likes_count': number;
    /**
     * この記事がストックされた数
     * @type {number}
     * @memberof QiitaPostDto
     */
    'stocks_count': number;
    /**
     * 記事に付いたタグ一覧
     * @type {Array<QiitaTagDto>}
     * @memberof QiitaPostDto
     */
    'tags': Array<QiitaTagDto>;
}
/**
 * 
 * @export
 * @interface QiitaTagDto
 */
export interface QiitaTagDto {
    /**
     * タグ名
     * @type {string}
     * @memberof QiitaTagDto
     */
    'name': string;
    /**
     * バージョン情報
     * @type {Array<string>}
     * @memberof QiitaTagDto
     */
    'versions': Array<string>;
}
/**
 * 
 * @export
 * @interface QiitaUserDto
 */
export interface QiitaUserDto {
    /**
     * ユーザーの一意なID
     * @type {string}
     * @memberof QiitaUserDto
     */
    'id': string;
    /**
     * 自己紹介文
     * @type {string}
     * @memberof QiitaUserDto
     */
    'description'?: string;
    /**
     * ユーザー名
     * @type {string}
     * @memberof QiitaUserDto
     */
    'name'?: string;
    /**
     * 設定しているプロフィール画像のURL
     * @type {string}
     * @memberof QiitaUserDto
     */
    'profile_image_url': string;
    /**
     * FacebookのID
     * @type {string}
     * @memberof QiitaUserDto
     */
    'facebook_id'?: string;
    /**
     * フォローしているユーザー数
     * @type {number}
     * @memberof QiitaUserDto
     */
    'followees_count': number;
    /**
     * フォロワー数
     * @type {number}
     * @memberof QiitaUserDto
     */
    'followers_count': number;
    /**
     * GitHubのログイン名
     * @type {string}
     * @memberof QiitaUserDto
     */
    'github_login_name'?: string;
    /**
     * 投稿した記事数
     * @type {number}
     * @memberof QiitaUserDto
     */
    'items_count': number;
    /**
     * LinkedInのID
     * @type {string}
     * @memberof QiitaUserDto
     */
    'linkedin_id'?: string;
    /**
     * 居住地
     * @type {string}
     * @memberof QiitaUserDto
     */
    'location'?: string;
    /**
     * 所属組織
     * @type {string}
     * @memberof QiitaUserDto
     */
    'organization'?: string;
    /**
     * 永続的なID
     * @type {number}
     * @memberof QiitaUserDto
     */
    'permanent_id': number;
    /**
     * チーム限定かどうか
     * @type {boolean}
     * @memberof QiitaUserDto
     */
    'team_only': boolean;
    /**
     * Twitterのスクリーン名
     * @type {string}
     * @memberof QiitaUserDto
     */
    'twitter_screen_name'?: string;
    /**
     * ウェブサイトURL
     * @type {string}
     * @memberof QiitaUserDto
     */
    'website_url'?: string;
}
/**
 * 
 * @export
 * @interface SearchQiitaPostsResponseDto
 */
export interface SearchQiitaPostsResponseDto {
    /**
     * 検索結果の記事一覧
     * @type {Array<QiitaPostDto>}
     * @memberof SearchQiitaPostsResponseDto
     */
    'posts': Array<QiitaPostDto>;
    /**
     * 検索結果の総件数
     * @type {number}
     * @memberof SearchQiitaPostsResponseDto
     */
    'totalCount': number;
    /**
     * 現在のページ番号
     * @type {number}
     * @memberof SearchQiitaPostsResponseDto
     */
    'page': number;
    /**
     * 1ページあたりの件数
     * @type {number}
     * @memberof SearchQiitaPostsResponseDto
     */
    'perPage': number;
}

/**
 * ProgramContentApiApi - axios parameter creator
 * @export
 */
export const ProgramContentApiApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 指定のヘッドライントピック番組を取得する
         * @param {string} id 
         * @param {string} authorization Bearer Token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHeadlineTopicProgram: async (id: string, authorization: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getHeadlineTopicProgram', 'id', id)
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('getHeadlineTopicProgram', 'authorization', authorization)
            const localVarPath = `/api/program-content/headline-topic-programs/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization != null) {
                localVarHeaderParameter['authorization'] = String(authorization);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary ヘッドライントピック番組の番組ID一覧を取得する
         * @param {string} authorization Bearer Token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHeadlineTopicProgramIds: async (authorization: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('getHeadlineTopicProgramIds', 'authorization', authorization)
            const localVarPath = `/api/program-content/headline-topic-program-ids`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization != null) {
                localVarHeaderParameter['authorization'] = String(authorization);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 指定のヘッドライントピック番組と、その類似番組および、前後の日付の番組を取得する
         * @param {string} id 
         * @param {string} authorization Bearer Token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHeadlineTopicProgramWithSimilarAndNeighbors: async (id: string, authorization: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getHeadlineTopicProgramWithSimilarAndNeighbors', 'id', id)
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('getHeadlineTopicProgramWithSimilarAndNeighbors', 'authorization', authorization)
            const localVarPath = `/api/program-content/headline-topic-programs/{id}/similar-and-neighbors`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization != null) {
                localVarHeaderParameter['authorization'] = String(authorization);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary ヘッドライントピック番組の一覧を取得する
         * @param {number} limit ページあたりに取得する番組の数
         * @param {string} authorization Bearer Token
         * @param {number} [page] ページ番号
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHeadlineTopicPrograms: async (limit: number, authorization: string, page?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'limit' is not null or undefined
            assertParamExists('getHeadlineTopicPrograms', 'limit', limit)
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('getHeadlineTopicPrograms', 'authorization', authorization)
            const localVarPath = `/api/program-content/headline-topic-programs`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (authorization != null) {
                localVarHeaderParameter['authorization'] = String(authorization);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary ヘッドライントピック番組の件数を取得する
         * @param {string} authorization Bearer Token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHeadlineTopicProgramsCount: async (authorization: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('getHeadlineTopicProgramsCount', 'authorization', authorization)
            const localVarPath = `/api/program-content/headline-topic-programs/count`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization != null) {
                localVarHeaderParameter['authorization'] = String(authorization);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProgramContentApiApi - functional programming interface
 * @export
 */
export const ProgramContentApiApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ProgramContentApiApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 指定のヘッドライントピック番組を取得する
         * @param {string} id 
         * @param {string} authorization Bearer Token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getHeadlineTopicProgram(id: string, authorization: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HeadlineTopicProgramDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getHeadlineTopicProgram(id, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProgramContentApiApi.getHeadlineTopicProgram']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary ヘッドライントピック番組の番組ID一覧を取得する
         * @param {string} authorization Bearer Token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getHeadlineTopicProgramIds(authorization: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<string>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getHeadlineTopicProgramIds(authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProgramContentApiApi.getHeadlineTopicProgramIds']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 指定のヘッドライントピック番組と、その類似番組および、前後の日付の番組を取得する
         * @param {string} id 
         * @param {string} authorization Bearer Token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getHeadlineTopicProgramWithSimilarAndNeighbors(id: string, authorization: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HeadlineTopicProgramWithSimilarAndNeighborsDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getHeadlineTopicProgramWithSimilarAndNeighbors(id, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProgramContentApiApi.getHeadlineTopicProgramWithSimilarAndNeighbors']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary ヘッドライントピック番組の一覧を取得する
         * @param {number} limit ページあたりに取得する番組の数
         * @param {string} authorization Bearer Token
         * @param {number} [page] ページ番号
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getHeadlineTopicPrograms(limit: number, authorization: string, page?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<HeadlineTopicProgramDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getHeadlineTopicPrograms(limit, authorization, page, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProgramContentApiApi.getHeadlineTopicPrograms']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary ヘッドライントピック番組の件数を取得する
         * @param {string} authorization Bearer Token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getHeadlineTopicProgramsCount(authorization: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HeadlineTopicProgramsCountDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getHeadlineTopicProgramsCount(authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProgramContentApiApi.getHeadlineTopicProgramsCount']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ProgramContentApiApi - factory interface
 * @export
 */
export const ProgramContentApiApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ProgramContentApiApiFp(configuration)
    return {
        /**
         * 
         * @summary 指定のヘッドライントピック番組を取得する
         * @param {string} id 
         * @param {string} authorization Bearer Token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHeadlineTopicProgram(id: string, authorization: string, options?: RawAxiosRequestConfig): AxiosPromise<HeadlineTopicProgramDto> {
            return localVarFp.getHeadlineTopicProgram(id, authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary ヘッドライントピック番組の番組ID一覧を取得する
         * @param {string} authorization Bearer Token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHeadlineTopicProgramIds(authorization: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<string>> {
            return localVarFp.getHeadlineTopicProgramIds(authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 指定のヘッドライントピック番組と、その類似番組および、前後の日付の番組を取得する
         * @param {string} id 
         * @param {string} authorization Bearer Token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHeadlineTopicProgramWithSimilarAndNeighbors(id: string, authorization: string, options?: RawAxiosRequestConfig): AxiosPromise<HeadlineTopicProgramWithSimilarAndNeighborsDto> {
            return localVarFp.getHeadlineTopicProgramWithSimilarAndNeighbors(id, authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary ヘッドライントピック番組の一覧を取得する
         * @param {number} limit ページあたりに取得する番組の数
         * @param {string} authorization Bearer Token
         * @param {number} [page] ページ番号
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHeadlineTopicPrograms(limit: number, authorization: string, page?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<HeadlineTopicProgramDto>> {
            return localVarFp.getHeadlineTopicPrograms(limit, authorization, page, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary ヘッドライントピック番組の件数を取得する
         * @param {string} authorization Bearer Token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHeadlineTopicProgramsCount(authorization: string, options?: RawAxiosRequestConfig): AxiosPromise<HeadlineTopicProgramsCountDto> {
            return localVarFp.getHeadlineTopicProgramsCount(authorization, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ProgramContentApiApi - object-oriented interface
 * @export
 * @class ProgramContentApiApi
 * @extends {BaseAPI}
 */
export class ProgramContentApiApi extends BaseAPI {
    /**
     * 
     * @summary 指定のヘッドライントピック番組を取得する
     * @param {string} id 
     * @param {string} authorization Bearer Token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProgramContentApiApi
     */
    public getHeadlineTopicProgram(id: string, authorization: string, options?: RawAxiosRequestConfig) {
        return ProgramContentApiApiFp(this.configuration).getHeadlineTopicProgram(id, authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary ヘッドライントピック番組の番組ID一覧を取得する
     * @param {string} authorization Bearer Token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProgramContentApiApi
     */
    public getHeadlineTopicProgramIds(authorization: string, options?: RawAxiosRequestConfig) {
        return ProgramContentApiApiFp(this.configuration).getHeadlineTopicProgramIds(authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 指定のヘッドライントピック番組と、その類似番組および、前後の日付の番組を取得する
     * @param {string} id 
     * @param {string} authorization Bearer Token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProgramContentApiApi
     */
    public getHeadlineTopicProgramWithSimilarAndNeighbors(id: string, authorization: string, options?: RawAxiosRequestConfig) {
        return ProgramContentApiApiFp(this.configuration).getHeadlineTopicProgramWithSimilarAndNeighbors(id, authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary ヘッドライントピック番組の一覧を取得する
     * @param {number} limit ページあたりに取得する番組の数
     * @param {string} authorization Bearer Token
     * @param {number} [page] ページ番号
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProgramContentApiApi
     */
    public getHeadlineTopicPrograms(limit: number, authorization: string, page?: number, options?: RawAxiosRequestConfig) {
        return ProgramContentApiApiFp(this.configuration).getHeadlineTopicPrograms(limit, authorization, page, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary ヘッドライントピック番組の件数を取得する
     * @param {string} authorization Bearer Token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProgramContentApiApi
     */
    public getHeadlineTopicProgramsCount(authorization: string, options?: RawAxiosRequestConfig) {
        return ProgramContentApiApiFp(this.configuration).getHeadlineTopicProgramsCount(authorization, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * QiitaPostsApi - axios parameter creator
 * @export
 */
export const QiitaPostsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Qiitaから指定条件に合致する記事を検索して取得します
         * @summary Qiita記事の検索
         * @param {Array<string>} [authors] 著者（カンマ区切りで複数指定可能）
         * @param {Array<string>} [tags] タグ（カンマ区切りで複数指定可能）
         * @param {string} [minPublishedAt] 公開日の最小値（YYYY-MM-DD形式）
         * @param {number} [page] ページ番号（1から始まる、デフォルト: 1）
         * @param {number} [perPage] 1ページあたりの件数（デフォルト: 20、最大: 100）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchQiitaPosts: async (authors?: Array<string>, tags?: Array<string>, minPublishedAt?: string, page?: number, perPage?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/qiita-posts/search`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authors) {
                localVarQueryParameter['authors'] = authors;
            }

            if (tags) {
                localVarQueryParameter['tags'] = tags;
            }

            if (minPublishedAt !== undefined) {
                localVarQueryParameter['minPublishedAt'] = (minPublishedAt as any instanceof Date) ?
                    (minPublishedAt as any).toISOString() :
                    minPublishedAt;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (perPage !== undefined) {
                localVarQueryParameter['perPage'] = perPage;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * QiitaPostsApi - functional programming interface
 * @export
 */
export const QiitaPostsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = QiitaPostsApiAxiosParamCreator(configuration)
    return {
        /**
         * Qiitaから指定条件に合致する記事を検索して取得します
         * @summary Qiita記事の検索
         * @param {Array<string>} [authors] 著者（カンマ区切りで複数指定可能）
         * @param {Array<string>} [tags] タグ（カンマ区切りで複数指定可能）
         * @param {string} [minPublishedAt] 公開日の最小値（YYYY-MM-DD形式）
         * @param {number} [page] ページ番号（1から始まる、デフォルト: 1）
         * @param {number} [perPage] 1ページあたりの件数（デフォルト: 20、最大: 100）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchQiitaPosts(authors?: Array<string>, tags?: Array<string>, minPublishedAt?: string, page?: number, perPage?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SearchQiitaPostsResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.searchQiitaPosts(authors, tags, minPublishedAt, page, perPage, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QiitaPostsApi.searchQiitaPosts']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * QiitaPostsApi - factory interface
 * @export
 */
export const QiitaPostsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = QiitaPostsApiFp(configuration)
    return {
        /**
         * Qiitaから指定条件に合致する記事を検索して取得します
         * @summary Qiita記事の検索
         * @param {Array<string>} [authors] 著者（カンマ区切りで複数指定可能）
         * @param {Array<string>} [tags] タグ（カンマ区切りで複数指定可能）
         * @param {string} [minPublishedAt] 公開日の最小値（YYYY-MM-DD形式）
         * @param {number} [page] ページ番号（1から始まる、デフォルト: 1）
         * @param {number} [perPage] 1ページあたりの件数（デフォルト: 20、最大: 100）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchQiitaPosts(authors?: Array<string>, tags?: Array<string>, minPublishedAt?: string, page?: number, perPage?: number, options?: RawAxiosRequestConfig): AxiosPromise<SearchQiitaPostsResponseDto> {
            return localVarFp.searchQiitaPosts(authors, tags, minPublishedAt, page, perPage, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * QiitaPostsApi - object-oriented interface
 * @export
 * @class QiitaPostsApi
 * @extends {BaseAPI}
 */
export class QiitaPostsApi extends BaseAPI {
    /**
     * Qiitaから指定条件に合致する記事を検索して取得します
     * @summary Qiita記事の検索
     * @param {Array<string>} [authors] 著者（カンマ区切りで複数指定可能）
     * @param {Array<string>} [tags] タグ（カンマ区切りで複数指定可能）
     * @param {string} [minPublishedAt] 公開日の最小値（YYYY-MM-DD形式）
     * @param {number} [page] ページ番号（1から始まる、デフォルト: 1）
     * @param {number} [perPage] 1ページあたりの件数（デフォルト: 20、最大: 100）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QiitaPostsApi
     */
    public searchQiitaPosts(authors?: Array<string>, tags?: Array<string>, minPublishedAt?: string, page?: number, perPage?: number, options?: RawAxiosRequestConfig) {
        return QiitaPostsApiFp(this.configuration).searchQiitaPosts(authors, tags, minPublishedAt, page, perPage, options).then((request) => request(this.axios, this.basePath));
    }
}



