/* tslint:disable */
/* eslint-disable */
/**
 * Tech Post Cast LIFF API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface ErrorResponseSchema
 */
export interface ErrorResponseSchema {
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseSchema
     */
    'message': string;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseSchema
     */
    'stackTrace'?: string;
}
/**
 * 
 * @export
 * @interface ListenerLetterSchema
 */
export interface ListenerLetterSchema {
    /**
     * 
     * @type {string}
     * @memberof ListenerLetterSchema
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof ListenerLetterSchema
     */
    'body': string;
    /**
     * 
     * @type {string}
     * @memberof ListenerLetterSchema
     */
    'penName': string;
    /**
     * 
     * @type {string}
     * @memberof ListenerLetterSchema
     */
    'sentAt': string;
}
/**
 * 
 * @export
 * @interface SendListenerLetterSchema
 */
export interface SendListenerLetterSchema {
    /**
     * 
     * @type {string}
     * @memberof SendListenerLetterSchema
     */
    'body': string;
    /**
     * 
     * @type {string}
     * @memberof SendListenerLetterSchema
     */
    'penName': string;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {SendListenerLetterSchema} [sendListenerLetterSchema] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiLiffListenerLettersPost: async (sendListenerLetterSchema?: SendListenerLetterSchema, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/liff/listener-letters`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(sendListenerLetterSchema, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {SendListenerLetterSchema} [sendListenerLetterSchema] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLiffListenerLettersPost(sendListenerLetterSchema?: SendListenerLetterSchema, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListenerLetterSchema>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiLiffListenerLettersPost(sendListenerLetterSchema, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiLiffListenerLettersPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @param {SendListenerLetterSchema} [sendListenerLetterSchema] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiLiffListenerLettersPost(sendListenerLetterSchema?: SendListenerLetterSchema, options?: RawAxiosRequestConfig): AxiosPromise<ListenerLetterSchema> {
            return localVarFp.apiLiffListenerLettersPost(sendListenerLetterSchema, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @param {SendListenerLetterSchema} [sendListenerLetterSchema] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiLiffListenerLettersPost(sendListenerLetterSchema?: SendListenerLetterSchema, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiLiffListenerLettersPost(sendListenerLetterSchema, options).then((request) => request(this.axios, this.basePath));
    }
}



