name: Deploy by AWS CDK

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
      runs-on: ubuntu-24.04
      steps:
        # リポジトリのコードをチェックアウト
        - name: Checkout
          uses: actions/checkout@v4
        # Node.js のセットアップ
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '20.18.1'
        - name: Create .env file
          run: echo "${{ secrets.ENVS }}" > .env.backend
        # Yarn のインストール
        - name: Install Yarn
          run: npm install -g yarn
        # 依存関係のインストール
        - name: Install dependencies
          run: yarn install
        # AWS CDK でのデプロイ
        - name: Deploy
          run: yarn deploy-infra-for-ci
          env:
            AWS_DEFAULT_REGION: 'ap-northeast-1'
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
